---
- name: Install bearded-avenger
  hosts: localhost
  become: True
  vars:
    smrt_provider: localhost
    zyre_group: darknet
    zsys_interface: enp0s8

  roles:
    - { role: ubuntu16, tags: role-ubuntu16 }

  tasks:


