---
- name: Install bearded-avenger
  hosts: localhost
  become: True
  vars:
    sshd_port: 2222
    # https://csirtg.io/signup
    # set values in ~/.profile or alike
    csirtg_token: "{{ lookup('env', 'CSIRTG_TOKEN') }}"
    csirtg_user: "{{ lookup('env', 'CSIRTG_USER') }}"
    csirtg_feed: "{{ lookup('env', 'CSIRTG_FEED') }}"

  pre_tasks:
    - name: install python
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  roles:
    - { role: ubuntu16, tags: role-ubuntu16 }

  tasks:


