---
- name: systemd env file
  template: src=darknet.env.j2 dest=/etc/darknet.env mode=0660 owner="{{ app_user }}" group="{{ app_user }}"

- name: systemd services
  copy: src={{ item }} dest=/etc/systemd/system owner=root group=root mode=0755
  with_items:
    - csirtg-ufw.service
  notify:
    - reload systemd

- name: enable services at boot
  service: name={{ item }} enabled=yes
  with_items:
    - csirtg-ufw.service