---
- name: systemd env file
  template: src=darknet.env.j2 dest=/etc/darknet.env mode=0660 owner="{{ app_user }}" group="{{ app_user }}"

- name: systemd services
  template: src=csirtg-ufw.service.j2 dest=/etc/systemd/system/csirtg-ufw.service owner=root group=root mode=0755
  notify:
    - reload systemd

- name: enable services at boot
  service: name={{ item }} enabled=yes
  with_items:
    - csirtg-ufw.service